### ISSUE TITLE
Lessons from Glium ergonomics

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#515]
Analyzing glium's [triangle](https://github.com/tomaka/glium/blob/master/examples/triangle.rs) example in comparison to [ours](https://github.com/gfx-rs/gfx-rs/blob/master/examples/triangle/main.rs#L88), I didn't discover any usability/ergonomics disasters. Here is what I see:
  1. [x] Glium has a simpler window initialization thanks to the full integration with Glutin. We had some integration with glfw/glutin at some point but then dropped it IIRC to make gfx more isolated. See #529 
  2. [x] Glium shaders are specified as the lowest version only (GLSL 1.10?), while gfx has 1.20 and 1.50 versions. Not really a big deal, since one can also specify just a lower version in gfx. Anyway, we need to work towards a more generic solution (see #71)
  3. [x] Glium has no batches, thus skipping a step. It pays for it by either being less safe (not validating batch consistency at init time), or introducing hidden caches for validated stuff. Either way, I prefer gfx way to validation.
  4. [x] Glium seems to have a simpler mesh structure: one vertex buffer and one index, no slices. Gfx is way more generic, and I strongly believe that is the right direction. We should continue looking into `Slice` ergonomics though. See #640 
  5. [x] Glium has a simpler `clear_color` function. Nothing stops us from having a similar one. See #141

**Comment by bjz** [comment]
Thanks for the analysis - I think ergonomics is really important for making gfx an attractive choice.

**Comment by kvark** [comment]
Update: (3) was implemented in #557

**Comment by kvark** [comment]
Update (2): we are now using both 120 and 150 version for the cube example

**Comment by kvark** [comment]
Everything was either fixed or moved to separate issues, closing.
