### ISSUE TITLE
Version 0.5

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#737]
Changes:
- [x] add multiple factories in #690
- [x] deprecate/remove `Canvas` in #704
- [x] `link_program_source` semantics
- [x] `create_buffer_*`, `update_buffer*` - some may need to be moved to `FactoryExt`
- [x] refactor shader parameter links in #738 
- [x] deprecate/remove `Graphics`
- [x] remove `IndexBuffer`
