### ISSUE TITLE
Version 0.6

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#745]
- [x] use `crates.io` for dependencies (#723)
- [x] remove global imports from examples (#744), cleanup `gfx::traits`
- [x] make `Renderer::update_*` to return a `Result` (#139)
- [x] remove `batch::Context` (#751)
- [x] make `Factory` clonable
- [ ] ~~change `clear()/blit()` semantics~~ (#630, possible to delay to 0.7)
